using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;
using VideoShelf.App.ViewModels;
using VideoShelf.Core.Models;
using VideoShelf.Core.Storage;

namespace VideoShelf.App.Harness;

/// <summary>
/// Drives the running app into a deterministic, screenshot-ready state for the
/// visual harness, then writes the done-signal file. UI-thread only.
/// Test-only: gated behind HarnessOptions.IsHarness in App.OnStartup.
/// </summary>
public sealed class HarnessRunner
{
    private readonly MainViewModel _main;
    private readonly HarnessOptions _options;
    private readonly LibraryRepository _library;
    private readonly WatchRepository _watch;
    private readonly TagRepository _tags;

    public HarnessRunner(
        MainViewModel main,
        HarnessOptions options,
        LibraryRepository library,
        WatchRepository watch,
        TagRepository tags)
    {
        _main = main;
        _options = options;
        _library = library;
        _watch = watch;
        _tags = tags;
    }

    public async Task RunAsync()
    {
        try
        {
            if (_options.Folder is not null)
                await AddSourceAsync(_options.Folder);
            if (_options.AutoStart || _options.Folder is not null)
                await ScanAndReloadAsync();

            if (_options.SeedDemo)
            {
                await SeedDemoAsync();
                await ScanAndReloadAsync();
            }

            await NavigateAsync(_options.View);
            await SettleAsync(isVideo: _options.View is "Player" or "PiP");
            WriteDoneSignal($"OK view={_options.View}");
        }
        catch (Exception ex)
        {
            WriteDoneSignal("ERROR: " + ex.Message);
        }
    }

    private async Task NavigateAsync(string view)
    {
        switch (view)
        {
            case "Home": _main.CurrentView = AppView.Home; break;
            case "Browse": _main.CurrentView = AppView.Browse; break;
            case "Settings": ShowSettings(); break;
            case "SectionDetail":
                await _main.OpenSectionAsync(FirstSectionId()); break;
            case "RenameTool":
                await _main.OpenRenameToolAsync(await LoadFirstSeriesAsync()); break;
            case "Player": await PlayAsync(_options.Play!, pip: false); break;
            case "PiP": await PlayAsync(_options.Play!, pip: true); break;
            default: _main.CurrentView = AppView.Home; break;
        }
    }

    private async Task SettleAsync(bool isVideo)
    {
        await Application.Current.Dispatcher.InvokeAsync(() => { }, DispatcherPriority.ContextIdle);
        await Task.Delay(isVideo ? 2500 : 700);
        await Application.Current.Dispatcher.InvokeAsync(() => { }, DispatcherPriority.ContextIdle);
    }

    private void WriteDoneSignal(string message)
    {
        if (_options.DoneSignal is null) return;
        try { File.WriteAllText(_options.DoneSignal, message + Environment.NewLine); }
        catch { }
    }

    // ---- Helpers wired to the real APIs ----

    /// <summary>
    /// Adds a folder source via LibraryRepository.UpsertSource (non-dialog path, same as
    /// SourcesViewModel.AddSource but without the IFolderPicker dialog).
    /// </summary>
    private Task AddSourceAsync(string folder)
    {
        var displayName = Path.GetFileName(folder.TrimEnd(Path.DirectorySeparatorChar))
            is { Length: > 0 } name ? name : folder;
        _library.UpsertSource(folder, displayName);
        _main.Sources.Load();
        return Task.CompletedTask;
    }

    /// <summary>
    /// Triggers MainViewModel.ScanAndReloadCommand (AsyncRelayCommand generated by [RelayCommand]
    /// on the private async Task ScanAndReload() method).
    /// </summary>
    private Task ScanAndReloadAsync()
        => _main.ScanAndReloadCommand.ExecuteAsync(null);

    /// <summary>
    /// Seeds demo data: marks the first video watched, sets a resume position on the second
    /// (if present), and tags the first section with "demo".
    /// </summary>
    private Task SeedDemoAsync()
    {
        var sources = _library.GetSources();
        if (sources.Count == 0) return Task.CompletedTask;

        foreach (var source in sources)
        {
            var sections = _library.GetSections(source.Id);
            if (sections.Count == 0) continue;

            // Tag the first section with "demo"
            _tags.AddTag(sections[0].Id, "demo");

            var seriesList = _library.GetSeriesForSection(sections[0].Id);
            if (seriesList.Count == 0) continue;

            var episodes = _library.GetEpisodes(seriesList[0].Id);
            if (episodes.Count == 0) continue;

            // Mark first episode watched
            _watch.SetWatched(episodes[0].VideoId, true);

            // Set a resume position on the second episode if present
            if (episodes.Count > 1)
                _library.SetResumePosition(episodes[1].VideoId, 30.0);

            break; // seed one source is sufficient for demo
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Returns the first section id from the loaded library sections, or 0 if none.
    /// Reads from Library.Sections (populated by ScanAndReloadAsync → LoadSectionsAsync).
    /// </summary>
    private long FirstSectionId()
        => _main.Library.Sections.FirstOrDefault()?.SectionId ?? 0;

    /// <summary>
    /// Returns the first SeriesViewModel from the first section. Loads series for the
    /// first section if not already loaded. Throws if none found (scan must find media).
    /// </summary>
    private async Task<SeriesViewModel> LoadFirstSeriesAsync()
    {
        var section = _main.Library.Sections.FirstOrDefault()
            ?? throw new InvalidOperationException("No sections found after scan.");

        if (section.SeriesList.Count == 0)
            await section.LoadSeriesAsync(BrowseSort.Name, CancellationToken.None);

        return section.SeriesList.FirstOrDefault()
            ?? throw new InvalidOperationException("No series found in first section.");
    }

    /// <summary>
    /// Shows settings by navigating to Home (Settings controls live in the sidebar,
    /// always visible; there is no separate AppView for settings).
    /// </summary>
    private void ShowSettings()
        => _main.CurrentView = AppView.Home;

    /// <summary>
    /// Plays a clip via MainViewModel.PlayEpisode(EpisodeView). Constructs a synthetic
    /// EpisodeView from the clip path (VideoId=0, SeriesId=0 — sufficient for engine.Load).
    /// If pip=true, sets IsPictureInPicture after playback starts (triggers MiniPlayerWindow).
    /// </summary>
    private async Task PlayAsync(string clip, bool pip)
    {
        var title = Path.GetFileNameWithoutExtension(clip);
        var episode = new EpisodeView(0L, 0L, clip, 1, title, false, false);
        _main.PlayEpisode(episode);

        if (pip)
        {
            // Let the player initialise before toggling PiP so the MediaPlayer is live.
            await Task.Delay(600);
            _main.IsPictureInPicture = true;
        }
    }
}
