using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;
using VideoShelf.App.ViewModels;
using VideoShelf.Core.Models;
using VideoShelf.Core.Storage;

namespace VideoShelf.App.Harness;

/// <summary>
/// Drives the running app into a deterministic, screenshot-ready state for the
/// visual harness, then writes the done-signal file. UI-thread only.
/// Test-only: gated behind HarnessOptions.IsHarness in App.OnStartup.
/// </summary>
public sealed class HarnessRunner
{
    private readonly MainViewModel _main;
    private readonly HarnessOptions _options;
    private readonly LibraryRepository _library;
    private readonly WatchRepository _watch;
    private readonly TagRepository _tags;

    public HarnessRunner(
        MainViewModel main,
        HarnessOptions options,
        LibraryRepository library,
        WatchRepository watch,
        TagRepository tags)
    {
        _main = main;
        _options = options;
        _library = library;
        _watch = watch;
        _tags = tags;
    }

    public async Task RunAsync()
    {
        try
        {
            if (_options.Folder is not null)
                await AddSourceAsync(_options.Folder);
            if (_options.AutoStart || _options.Folder is not null)
                await ScanAndReloadAsync();

            if (_options.SeedDemo)
            {
                await SeedDemoAsync();
                await ScanAndReloadAsync();
            }

            await NavigateAsync(_options.View);
            await SettleAsync(isVideo: _options.View is "Player" or "PiP");
            WriteDoneSignal($"OK view={_options.View}");
        }
        catch (Exception ex)
        {
            WriteDoneSignal("ERROR: " + ex.Message);
        }
    }

    private async Task NavigateAsync(string view)
    {
        switch (view)
        {
            case "Home": _main.CurrentView = AppView.Home; break;
            case "Browse": _main.CurrentView = AppView.Browse; break;
            case "Settings": ShowSettings(); break;
            case "SectionDetail":
                await _main.OpenSectionAsync((await FindRichestSeriesAsync()).SectionId);
                var expandable = _main.SectionDetail.SeriesList.FirstOrDefault(s => !s.IsStandalone);
                if (expandable is not null) await expandable.ActivateCommand.ExecuteAsync(null);
                break;
            case "RenameTool":
                await _main.OpenRenameToolAsync((await FindRichestSeriesAsync()).Series); break;
            case "Player": await PlayAsync(_options.Play!, pip: false); break;
            case "PiP": await PlayAsync(_options.Play!, pip: true); break;
            case "Search": await NavigateSearchAsync(); break;
            default: _main.CurrentView = AppView.Home; break;
        }
    }

    /// <summary>
    /// Seeds the Search view with a term matching the first scanned creator so the
    /// Creators section is populated for the screenshot sweep.
    /// </summary>
    private async Task NavigateSearchAsync()
    {
        var summaries = _library.GetSectionSummaries();
        var term = summaries.Count > 0 ? summaries[0].DisplayName : "video";
        _main.Search.Query = term;
        await _main.Search.WaitForIdleAsync();
    }

    private async Task SettleAsync(bool isVideo)
    {
        await Application.Current.Dispatcher.InvokeAsync(() => { }, DispatcherPriority.ContextIdle);
        await Task.Delay(isVideo ? 2500 : 700);
        await Application.Current.Dispatcher.InvokeAsync(() => { }, DispatcherPriority.ContextIdle);
    }

    private void WriteDoneSignal(string message)
    {
        if (_options.DoneSignal is null) return;
        try { File.WriteAllText(_options.DoneSignal, message + Environment.NewLine); }
        catch { }
    }

    // ---- Helpers wired to the real APIs ----

    /// <summary>
    /// Adds a folder source via LibraryRepository.UpsertSource (non-dialog path, same as
    /// SourcesViewModel.AddSource but without the IFolderPicker dialog).
    /// </summary>
    private Task AddSourceAsync(string folder)
    {
        var displayName = Path.GetFileName(folder.TrimEnd(Path.DirectorySeparatorChar))
            is { Length: > 0 } name ? name : folder;
        _library.UpsertSource(folder, displayName);
        _main.Sources.Load();
        return Task.CompletedTask;
    }

    /// <summary>
    /// Triggers MainViewModel.ScanAndReloadCommand (AsyncRelayCommand generated by [RelayCommand]
    /// on the private async Task ScanAndReload() method).
    /// </summary>
    private Task ScanAndReloadAsync()
        => _main.ScanAndReloadCommand.ExecuteAsync(null);

    /// <summary>
    /// Seeds demo data: marks the first video watched, sets a resume position on the second
    /// (if present), and tags the first section with "demo".
    /// </summary>
    private Task SeedDemoAsync()
    {
        var sources = _library.GetSources();
        if (sources.Count == 0) return Task.CompletedTask;

        foreach (var source in sources)
        {
            var sections = _library.GetSections(source.Id);
            if (sections.Count == 0) continue;

            // Tag EVERY section with "demo" so that, once a video in one section is marked
            // watched (below), the OTHER unwatched sections share that tag's affinity and
            // surface in the For-you / Recommended-creators / Recommended-videos rails.
            // (Tagging only one section left those rails empty — GetForYou needs a watched,
            // tagged section to build affinity AND a distinct unwatched section sharing it.)
            foreach (var section in sections) _tags.AddTag(section.Id, "demo");

            // Seed watched+resume on the richest series available (the most episodes),
            // not blindly sections[0]'s first series — that section may hold only
            // single-file standalones, leaving the continue-watching rail empty.
            var richest = sections
                .SelectMany(s => _library.GetSeriesForSection(s.Id))
                .Select(se => _library.GetEpisodes(se.Id))
                .Where(eps => eps.Count > 0)
                .OrderByDescending(eps => eps.Count)
                .FirstOrDefault();
            if (richest is null) continue;

            // Mark first episode watched
            _watch.SetWatched(richest[0].VideoId, true);

            // Set a partial resume position on the second episode if present (populates
            // the continue-watching rail with a visibly partial progress bar). Falls back
            // to the first video for a standalone so the rail is still exercised.
            if (richest.Count > 1)
                _library.SetResumePosition(richest[1].VideoId, 12.0);
            else
                _library.SetResumePosition(richest[0].VideoId, 12.0);

            break; // seed one source is sufficient for demo
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Finds the series with the most episodes across all sections (so the SectionDetail
    /// and RenameTool shots land on a meaningful multi-episode series rather than a
    /// single-file standalone). Loads each section's series list on demand. Throws if the
    /// scan found no media.
    /// </summary>
    private async Task<(long SectionId, SeriesViewModel Series)> FindRichestSeriesAsync()
    {
        (long SectionId, SeriesViewModel Series)? best = null;
        foreach (var section in _main.Library.Sections)
        {
            if (section.SeriesList.Count == 0)
                await section.LoadSeriesAsync(BrowseSort.Name, CancellationToken.None);

            foreach (var series in section.SeriesList)
            {
                if (best is null || series.EpisodeCount > best.Value.Series.EpisodeCount)
                    best = (section.SectionId, series);
            }
        }

        return best ?? throw new InvalidOperationException("No series found after scan.");
    }

    /// <summary>
    /// Shows settings by navigating to Home (Settings controls live in the sidebar,
    /// always visible; there is no separate AppView for settings).
    /// </summary>
    private void ShowSettings()
        => _main.CurrentView = AppView.Home;

    /// <summary>
    /// Plays a clip via MainViewModel.PlayEpisode(EpisodeView). Constructs a synthetic
    /// EpisodeView from the clip path (VideoId=0, SeriesId=0 — sufficient for engine.Load).
    /// If pip=true, sets IsPictureInPicture after playback starts (activates PiP mode in PlayerView).
    /// </summary>
    private async Task PlayAsync(string clip, bool pip)
    {
        // Play a REAL scanned episode (DB-backed VideoId + on-disk path) rather than a
        // synthetic EpisodeView: the player's missing-file guard rejects ids that aren't
        // in the library, so a fabricated episode renders the "File not found" banner.
        // The first episode of the richest series (e.g. Big Buck Bunny 1) is a known clip.
        var (_, series) = await FindRichestSeriesAsync();
        var episode = _library.GetEpisodes(series.SeriesId).FirstOrDefault()
            ?? throw new InvalidOperationException("Richest series has no episodes to play.");
        _main.PlayEpisode(episode);

        if (pip)
        {
            // Let the player initialise before toggling PiP so the MediaPlayer is live.
            await Task.Delay(600);
            _main.IsPictureInPicture = true;
        }
    }
}
